version: '3'

services:
  backend:
    networks:
      - proxy_app-network
    build:
      context: ./backend
      dockerfile: Dockerfile
    mem_limit: 512M
    ports:
      - "5003:5000"
    environment:
      - NODE_ENV
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_USER
      - MONGO_PASS
      - JWT_SECRET
      - RECAPTCHA_SECRET_KEY
      - VIRTUAL_HOST=api.answermillion.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.answermillion.com
      - LETSENCRYPT_EMAIL=jason@mavacode.com
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
    networks:
      - proxy_app-network
    build:
      context: ./frontend
      args:
        - NODE_ENV
      dockerfile: Dockerfile
    mem_limit: 2048M
    user: "1000:1000"
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV
      - REACT_APP_API_URL
      - REACT_APP_S3_BASE_URL
      - REACT_APP_RECAPTCHA_SITE_KEY
      - VIRTUAL_HOST=answermillion.com,www.answermillion.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=answermillion.com,www.answermillion.com
      - LETSENCRYPT_EMAIL=jason@mavacode.com
    restart: always

  mongodb:
    networks:
      - proxy_app-network
    image: mongo:latest
    mem_limit: 128M
    ports:
      - "27017:27017" # Maps port 27017 of the host to port 27017 of the container
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    restart: always

networks:
  proxy_app-network:
    external: true

